spring.application.name=Ecomm

# Database URL with local fallback
spring.datasource.url=jdbc:postgresql://${SPRING_DATASOURCE_URL:localhost:5432/ecommerce}
# Database Username with local fallback
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
# Database Password with local fallback
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Keeps your Hibernate/JPA settings intact
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
