spring.application.name=Ecomm

# Database URL with local fallback
spring.datasource.url=jdbc:mysql://${SPRING_DATASOURCE_URL:localhost:3306/ecommerce}
# Database Username with local fallback
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
# Database Password with local fallback
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Keeps your Hibernate/JPA settings intact
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
